<?php
/**
 * @file
 * ny2014_feature.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function ny2014_feature_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "ds" && $api == "ds") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function ny2014_feature_views_api($module = NULL, $api = NULL) {
  return array("api" => "3.0");
}

/**
 * Implements hook_node_info().
 */
function ny2014_feature_node_info() {
  $items = array(
    'greeting' => array(
      'name' => t('Greeting'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Name'),
      'help' => '',
    ),
  );
  return $items;
}
